# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:

    runs-on: macos-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Feather
      run: swift build -v

    - name: Run Unit Tests
      run: swift test -v

  ui-tests:

    runs-on: macos-latest
    # needs:
    #   - unit-tests

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2.0'
    #
    # - name: Create Simulator
    #   run: xcrun simctl create iPhoneTestDevice com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-16-2
    #
    # - name: Boot Simulator
    #   run:  xcrun simctl boot iPhoneTestDevice
    #   # uses: futureware-tech/simulator-action@v2
    #   # with:
    #   #   model: 'iPhoneTestDevice'
    #   #   os: 'iOS'
    #   #   os_version: '16.2'

    # - name: List Simulators
    #   run: xcrun simctl list devices

    - name: Run UI Tests
      run: |
        cd Demo
        ./create_sim.sh
